cardinal namespaces indexing
holaplex/indexer pull request #392
Opened 2022-04-22 21:53 UTC by dandlezzz

Adds cardinal namespace indexing to our beloved indexer

2022-04-22 22:15 UTC, ray-kast requested changes

2022-04-22 22:15 UTC, ray-kast commented on crates/core/migrations/2022-04-22-182428_add_source_column_to_twitter_handles/down.sql
> +
```suggestion
```

2022-04-22 22:15 UTC, ray-kast commented on crates/core/migrations/2022-04-22-182428_add_source_column_to_twitter_handles/down.sql
> +drop column write_version;
```suggestion
drop column from_bonfida
drop column from_cardinal
drop column write_version;
```

2022-04-22 22:15 UTC, ray-kast commented on crates/core/migrations/2022-04-22-182428_add_source_column_to_twitter_handles/up.sql
> +add column write_version bigint not null default 0;
```suggestion
add column from_bonfida boolean not null default true
add column from_cardinal boolean not null default false
add column write_version bigint not null default 0;
```

2022-04-25 13:23 UTC, imabdulbasit approved these changes

2022-04-25 18:51 UTC, ray-kast approved these changes

2022-04-25 18:51 UTC, merged