Query NFTs by collection
holaplex/indexer pull request #421
Opened 2022-04-29 16:47 UTC by imabdulbasit

2022-04-29 21:55 UTC, ray-kast approved these changes

2022-05-04 11:30 UTC, kespinola requested changes
Like to release with limits and offset for the nfts field on collections.

2022-05-04 11:30 UTC, kespinola commented on crates/graphql/src/schema/objects/collection.rs
> +    }
Need to get limit and offset as arguments for this field or going to be returning thousands of nfts.

2022-05-07 06:11 UTC, kespinola commented
Chatted in standup Thursday but for v1 of filtering nfts by collections about allowing subquery but returning all the addresses of nfts belonging to a collection to filter the existing query is going result of 10K plus address being returned for a pfp project for example. Does this sound right @imabdulbasit?

2022-05-07 10:25 UTC, imabdulbasit commented
> Chatted in standup Thursday but for v1 of filtering nfts by collections about allowing subquery but returning all the addresses of nfts belonging to a collection to filter the existing query is going result of 10K plus address being returned for a pfp project for example. Does this sound right @imabdulbasit?

We already pass collection mint address as filter. So if the filter passes collection metadata address, we need the mint address and for that we need a separate query which will return one mint address of a collection and use the same filter like we have.

2022-05-17 23:54 UTC, ray-kast requested changes
Branch needs to be rebased to accommodate a new CI step.

2022-05-31 19:23 UTC, closed without merging