deploy
holaplex/indexer pull request #433
Opened 2022-05-03 17:01 UTC by dandlezzz

lots of minor fixes and some better dialect support

2022-05-03 17:21 UTC, ray-kast requested changes
Working on not making the indexer crash if you don't provide Dialect env vars

2022-05-03 18:17 UTC, kespinola approved these changes
g2g on my end got marketplace app running in docker again.

2022-05-04 18:18 UTC, mpwsh approved these changes

2022-05-04 18:30 UTC, ray-kast approved these changes

2022-05-04 20:13 UTC, merged