Auction house instructions indexing
holaplex/indexer pull request #506
Opened 2022-06-02 16:38 UTC by imabdulbasit

2022-06-06 11:44 UTC, kespinola approved these changes
Great work.

2022-06-06 11:44 UTC, kespinola commented on crates/indexer/src/geyser/instructions/buy.rs
> +        .context("failed to insert buy instruction ")?;
In future move this to a transaction?

2022-06-06 11:44 UTC, kespinola commented on crates/indexer/src/geyser/instructions/cancel.rs
> +use mpl_auction_house::instruction::Cancel;
Nice getting the cancel struct from the program 👍

2022-06-06 22:02 UTC, ray-kast requested changes
Are there any tables we need to add the `check_slot_wv` trigger to?

2022-06-08 20:28 UTC, ray-kast requested changes
Looks good.  Still gonna advocate for the use of `check_slot_wv` - we can use `-1` as a fallback for any instructions that don't have these fields.

2022-06-16 22:42 UTC, ray-kast approved these changes

2022-06-16 23:57 UTC, merged