Refactor Wallet Activities Query
holaplex/indexer pull request #698
Opened 2022-08-25 11:42 UTC by alchemistgo87

- Add limit, offset, event types as variables to wallet activities query
- Remove cancelled_listing event from wallet activities query

2022-08-25 15:16 UTC, kespinola approved these changes
nice. way to get the pagination and event_types in 👍

2022-08-25 21:45 UTC, kespinola requested changes
@alchemistgo87 what is using this query right now? I'm think what UI will break from this change.

2022-08-26 06:02 UTC, alchemistgo87 commented
> @alchemistgo87 what is using this query right now? I'm think what UI will break from this change.

I suppose right now this can only break the current profile activity page at holaplex.com

2022-08-26 07:08 UTC, kespinola commented on crates/core/src/db/queries/wallet.rs
> +    println!("Query Result: {:?}", query);
This println should be dropped.

2022-08-26 14:02 UTC, kespinola commented
https://github.com/holaplex/holaplex/pull/701

Holaplex updated to work with pagination.

2022-08-26 14:03 UTC, kespinola approved these changes

2022-08-26 14:13 UTC, merged