Moonrank collections indexing
holaplex/indexer pull request #816
Opened 2022-10-12 02:05 UTC by imabdulbasit

2022-10-12 17:29 UTC, imabdulbasit commented on crates/moonrank/Cargo.toml
> +tokio = { version = "1.13.0", features = ["macros", "rt", "rt-multi-thread", "signal", "sync", "full"] }
I was trying something else which required more features. I am not using most of these

2022-10-13 07:13 UTC, kespinola requested changes
Looks great just the additional fields to save on collections. Thank you.

2022-10-13 07:13 UTC, kespinola commented on crates/core/src/db/models.rs
> +    pub updated_at: NaiveDateTime,
There are some additional fields that I'd like to index. Can you include this set please?

```
id [primary key]
image 
name
description
twitter_url
discord_url
website_url
magic_eden_identifier [index]
verified
pieces
go_live_at
verified_collection_address
created_at
updated_at
```

2022-10-13 16:40 UTC, kespinola reviewed
Looks good. Seems like all we need now is to build the binary in the docker file and add its docker script for the startup.

2022-10-13 16:43 UTC, mpwsh submitted a review, later dismissed

2022-10-13 20:33 UTC, kespinola approved these changes

2022-10-14 19:49 UTC, mpwsh approved these changes

2022-10-14 20:08 UTC, merged