Wallet Rewards Lookup
holaplex/indexer pull request #828
Opened 2022-10-17 12:12 UTC by alchemistgo87

Addresses: #812

2022-10-17 12:15 UTC, kespinola requested changes
need to handle init creation of the records.

2022-10-17 12:15 UTC, kespinola commented on crates/core/migrations/2022-10-17-074109_create_wallet_total_rewards_table/up.sql
> +    where reward_center_address = new.reward_center;
Needs to handle creating the record for the buyer or the seller when it doesn't exists

2022-10-17 14:03 UTC, imabdulbasit commented on crates/core/migrations/2022-10-17-074109_create_wallet_total_rewards_table/up.sql
> +            where wallet_address = new.buyer
I don't see wallet_address column in reward_payouts table

2022-10-17 19:06 UTC, kespinola requested changes
looks good just 1 item on scoping column by table name.

2022-10-17 19:06 UTC, kespinola commented on crates/core/migrations/2022-10-17-074109_create_wallet_total_rewards_table/up.sql
> +    do update set total_reward = total_reward + new.seller_reward;
```suggestion
    on conflict (wallet_address, reward_center_address)
    do update set total_reward = wallet_total_rewards.total_reward + new.buyer_reward;

    insert into wallet_total_rewards values (new.seller, new.reward_center, new.seller_reward)
    on conflict (wallet_address, reward_center_address)
    do update set total_reward = wallet_total_rewards.total_reward + new.seller_reward;
```

Get ambiguous error when postgres executes the function unless include the table name.

2022-10-18 12:46 UTC, imabdulbasit approved these changes

2022-10-19 18:14 UTC, kespinola approved these changes

2022-10-19 18:14 UTC, merged